/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lab04;

/**
 *
 * @author MjING
 */
public class Calculator extends javax.swing.JFrame {

    /**
     * Creates new form Calculator
     */
    public Calculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        display = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButtonADD = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButtonSUB = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButtonMUL = new javax.swing.JButton();
        jButtonDECS = new javax.swing.JButton();
        jButton0 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButtonDiv = new javax.swing.JButton();
        jButtonROOT = new javax.swing.JButton();
        jButtonCLR = new javax.swing.JButton();
        jButtonAWSCLR = new javax.swing.JButton();
        jButtonEQ = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        Quit = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        About = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        display.setEditable(false);
        display.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        display.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        display.setMargin(new java.awt.Insets(15, 15, 15, 15));
        display.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayActionPerformed(evt);
            }
        });
        getContentPane().add(display, java.awt.BorderLayout.PAGE_START);

        jPanel1.setLayout(new java.awt.GridLayout(5, 4));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalculatorButtonPressed(evt);
            }
        });
        jPanel1.add(jButton1);

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton2.setText("2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalculatorButtonPressed(evt);
            }
        });
        jPanel1.add(jButton2);

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton3.setText("3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalculatorButtonPressed(evt);
            }
        });
        jPanel1.add(jButton3);

        jButtonADD.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonADD.setText("+");
        jButtonADD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalculatorButtonPressed(evt);
            }
        });
        jPanel1.add(jButtonADD);

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton4.setText("4");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalculatorButtonPressed(evt);
            }
        });
        jPanel1.add(jButton4);

        jButton5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton5.setText("5");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalculatorButtonPressed(evt);
            }
        });
        jPanel1.add(jButton5);

        jButton6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton6.setText("6");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalculatorButtonPressed(evt);
            }
        });
        jPanel1.add(jButton6);

        jButtonSUB.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonSUB.setText("-");
        jButtonSUB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalculatorButtonPressed(evt);
            }
        });
        jPanel1.add(jButtonSUB);

        jButton7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton7.setText("7");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalculatorButtonPressed(evt);
            }
        });
        jPanel1.add(jButton7);

        jButton8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton8.setText("8");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalculatorButtonPressed(evt);
            }
        });
        jPanel1.add(jButton8);

        jButton9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton9.setText("9");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalculatorButtonPressed(evt);
            }
        });
        jPanel1.add(jButton9);

        jButtonMUL.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonMUL.setText("x");
        jButtonMUL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalculatorButtonPressed(evt);
            }
        });
        jPanel1.add(jButtonMUL);

        jButtonDECS.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonDECS.setText(".");
        jButtonDECS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalculatorButtonPressed(evt);
            }
        });
        jPanel1.add(jButtonDECS);

        jButton0.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton0.setText("0");
        jButton0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalculatorButtonPressed(evt);
            }
        });
        jPanel1.add(jButton0);

        jButton15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton15.setText("*");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalculatorButtonPressed(evt);
            }
        });
        jPanel1.add(jButton15);

        jButtonDiv.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonDiv.setText("÷");
        jButtonDiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalculatorButtonPressed(evt);
            }
        });
        jPanel1.add(jButtonDiv);

        jButtonROOT.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonROOT.setText("√");
        jButtonROOT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalculatorButtonPressed(evt);
            }
        });
        jPanel1.add(jButtonROOT);

        jButtonCLR.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonCLR.setText("C");
        jButtonCLR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalculatorButtonPressed(evt);
            }
        });
        jPanel1.add(jButtonCLR);

        jButtonAWSCLR.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonAWSCLR.setText("AC");
        jButtonAWSCLR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalculatorButtonPressed(evt);
            }
        });
        jPanel1.add(jButtonAWSCLR);

        jButtonEQ.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonEQ.setText("=");
        jButtonEQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalculatorButtonPressed(evt);
            }
        });
        jPanel1.add(jButtonEQ);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jMenu1.setText("File");

        Quit.setText("Quit");
        Quit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuitActionPerformed(evt);
            }
        });
        jMenu1.add(Quit);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        About.setText("About");
        About.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AboutActionPerformed(evt);
            }
        });
        jMenu2.add(About);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AboutActionPerformed
        javax.swing.JOptionPane.showMessageDialog(null,"Mason 11/1/2024");
    }//GEN-LAST:event_AboutActionPerformed

    private void QuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_QuitActionPerformed

    private void CalculatorButtonPressed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalculatorButtonPressed
        onButtonPressed((javax.swing.JButton)evt.getSource());
    }//GEN-LAST:event_CalculatorButtonPressed

    private void displayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_displayActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Calculator().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu About;
    private javax.swing.JMenu Quit;
    private javax.swing.JTextField display;
    private javax.swing.JButton jButton0;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButtonADD;
    private javax.swing.JButton jButtonAWSCLR;
    private javax.swing.JButton jButtonCLR;
    private javax.swing.JButton jButtonDECS;
    private javax.swing.JButton jButtonDiv;
    private javax.swing.JButton jButtonEQ;
    private javax.swing.JButton jButtonMUL;
    private javax.swing.JButton jButtonROOT;
    private javax.swing.JButton jButtonSUB;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
 private double result;
private char operation;
private boolean error;
private int displayLen;
private String disp;
public static final int MAX_DISPLAY_LEN = 10;
public static final double MAX_VALUE_EXCLUSIVE = 10000000000.0;
private void allClear ()
{
	result = 0.0;
	operation = '+';
	error = false ;
	displayLen = 0;
	disp = " " ;
}
// Avoids " scientific notation " format for large numbers ;
// and guaranteed to give us too many digits . We then just
// truncate away the ones we don 't need .
private String toDisplayString(double d)
{
	String asStr = String.format( "%." + (MAX_DISPLAY_LEN) + "f" ,d);
	int maxLen = MAX_DISPLAY_LEN;
	if (asStr.charAt(0) == '-') 
	{
		maxLen += 1;
	}
	asStr = asStr.substring(0, maxLen);
	return asStr;
}
private void updateDisplay()
{
	if (error)
	{
		display.setText("Err");
	}
	else if (displayLen > 0)
	{
		display.setText(disp);
	}
	else
	{
		display.setText(toDisplayString(result));
	}
}
private void exec(double immediateValue)
{
	System.out.println(result);
	System.out.println(operation);
	System.out.println(immediateValue);
	switch(operation)
	{
		case '=' -> result = immediateValue;
		case '+' -> result += immediateValue;
		case '-' -> result -= immediateValue;
		case 'x' -> result *= immediateValue ;
		case '÷' -> {
                    if (immediateValue == 0)
                    {
                        error = true;
                    }
                    else
                    {
                        result /= immediateValue;
                    }
            }
	}
	System.out.println(":= > " + result);
	double check = Math.abs(result);
	if (check >= MAX_VALUE_EXCLUSIVE)
	{
		error = true;
	}
	displayLen = 0;
	disp = "";
}
private void handlePress(char code)
{
	if (code == 'A')
	{
		allClear();
		return;
	}
	if (error)
	{
		return;
	}
	if (code == 'C')
	{
		disp = "";
		displayLen = 0;
	}
	else if (code >= '0' && code <= '9' || code == '.') 
	{
		if (code == '.' && disp.indexOf('.') != -1)
		{
			// Just ignore the button press ; can 't have more than one '. '
			// This is sometimes called " eating " user input .
		}
		else if (displayLen < MAX_DISPLAY_LEN + (code == '.' ? 1 : 0) )
		{
			// special case - if disp is "0" , just overwrite it .
			if ("0".equals(disp) && code != '.')
			{
				disp = "" + code;
			}
			else
			{
				disp += code;
				displayLen += 1;
			}
		}
	}
	else if (code == 'r' || code == '±')
	{
		double value = displayLen == 0 ? result : Double.parseDouble(disp);
		final double intermediate;
		if (code == 'r')
		{
			if (value < 0)
			{
				error = true;
				return;
			}
			intermediate = Math.sqrt(value);
		}
		else
		{
			intermediate = -value;
		}
		disp = toDisplayString(intermediate);
		displayLen = disp.length();
	}
	else
	{
		double value = displayLen == 0 ? result : Double.parseDouble(disp);
		exec(value);
		operation = code;
	}
}
private void onButtonPressed(javax.swing.JButton which)
{
	// Step 1 - Turn ` which ` into a letter
	String buttonText = which.getText();
	final char letter;
	if ("<html>&radic;</html>".equals(buttonText) || "√".equals(buttonText))
	{
		letter = 'r';
	}
	else
	{
		letter = buttonText.charAt(0);
	}
	// Step 2 - Apply the effect of that button ( see the " Background "
	// section in the handout ) .
	handlePress(letter);
	// Step 3 - change what 's shown in the ` display ` JTextField .
	updateDisplay();
}
}
